### ISSUE TITLE
create unit tests for terraform client

### ISSUE THREAD

**Issue by waleedhammam** [threefoldfoundation/www_owncloud#13]
will be useful and should be merged to js-sdk soon too

**Comment by sameh-farouk** [comment]
**Status Update:**
Happy path tests were implemented here https://github.com/threefoldtech/owncloud_deployer/commit/a5f727beb019aa0ab389d85597d30611c7a232e5

**Comment by sameh-farouk** [comment]
**Status Update:**

Initial sad path tests were implemented here https://github.com/threefoldtech/owncloud_deployer/commit/13d5890959a6c710a3e3252c80738af4ebc85c59
