### ISSUE TITLE
re-wording

### ISSUE THREAD

**Issue by rkhamis** [threefoldfoundation/www_owncloud#6]
- [x] in the image: change text to say "Welcome to the Freemium Owncloud Deployer"

- [x] change "_Please enter your email to get creds and domain for you instance on. If not provided email TF connect will be used_" ---> 
   "<user's email> will be used to send you your deployment information. If you prefer to receive emails on a different address, fill in below"

- [x] "Agree at Terms & Conditions" ---> "I have read and I accept the terms and conditions"
- [x] "Thanks for submission, Request will be processed soon." ----> "Your request will be processed soon. You'll receive your deployment information at <configured email>"
- [x] "user x has already submitted request before" ----> "user x has already submitted a request. please be patient while we prepare your deployment"

- [x] email text:
   "
   Dear x,

   Your Owncloud instance will be ready in few minutes, please use these credentials to access it.
    Domain:....
    Admin username: ...
    Admin password: ..."
    
 - [x] expiration email text:
 "Dear x,
  Your deployment <domain> has expired"

**Comment by waleedhammam** [comment]
![Screenshot from 2022-02-06 16-00-14](https://user-images.githubusercontent.com/10658229/152684793-3131ffdb-e197-45dc-b6f1-d9568d81973f.png)
